pipeline {
    agent any
    triggers {
        pollSCM('H/5 * * * *')
    }
    stages {
        stage('Hello world') {
            steps {
                echo "Running some test..."
            }
        }
    }
    stages {
        stage('Hello world, again') {
            steps {
                echo "Running another test..."
            }
        }
    }
}
