pipeline {
    agent any
    triggers {
        pollSCM('H/5 * * * *')
    }
    stages {
        stage('Checkout') {
            steps {
                //git url: 'https://github.com/aweiteka/jenkins-on-openshift.git'
                // only checkout if Jenkins config has changed altogether
                checkout([$class: 'GitSCM',
                    branches: [[name: "*/multi-pipeline"]],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [[
                        $class: 'PathRestriction',
                        includedRegions: '^jenkins/pipelines/.*']],
                    submoduleCfg: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/aweiteka/jenkins-on-openshift']]])
            }
        }
        stage('Trigger build') {
            steps {
                //openshiftBuild bldCfg: 'jenkins-custom'
                echo 'Tiggering build'
            }
        }
        stage('Trigger deployment') {
            steps {
                //openshiftDeploy depCfg: 'jenkins'
                echo 'triggering deployment'
            }
        }
    }
}
